app/urls.py
from django.urls import path
import app.views as views
app_name = 'app'

urlpatterns = [
    path('<identifier>/', views.ProfileView.as_view(), name='profile'),
    path('p/<uuid>/', views.PostDetailView.as_view(), name='post'),
    path("follow/<identifier>/", views.Follow.as_view(), name="follow"),
    path("unfollow/<identifier>/", views.Unfollow.as_view(), name="unfollow"),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

users/urls.py
from django.urls import path, reverse_lazy, include
from django.contrib.auth import views as auth_views
import users.views as views
from users.forms import LoginForm
app_name = 'users'

#https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html

urlpatterns = [
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('identifier_validation/', views.ValidateIdentififer.as_view(), name='validate_identifier'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html', authentication_form = LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/',views.MyPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
import PIL.Image as Image

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
#https://django-ratelimit.readthedocs.io/en/stable/

class UserManager(BaseUserManager):
    def create_user(self, identifier, email, password):
        if not identifier or not email:
            raise ValueError('Identifier and/or Email missing!')
        user = self.model(
            identifier = identifier,
            email = self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, identifier, email, password):
        user = self.create_user(
            identifier,
            email,
            password=password
        )
        user.is_superuser = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    identifier = models.CharField(
        #human-readable name
        verbose_name = 'username',
        max_length=30,
        unique=True)
    email = models.EmailField(max_length=50, unique = True)
    name = models.CharField(max_length=35, blank=True, null=True)
    profile_info = models.TextField(max_length = 1000, blank=True, null=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'identifier'
    REQUIRED_FIELDS = ['password', 'email']
    #EMAIL_FIELD --> defaults to email

    def __str__(self):
        return self.identifier

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self._password is not None:
            password_validation.password_changed(self._password, self)
            self._password = None
        picture = Image.open(self.profile_pic)
        picture = picture.resize((150, 150), Image.ANTIALIAS)
        picture.save(self.profile_pic.path)


    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_absolute_url(self):
        return reverse('users:login')

    @property
    def is_staff(self):
        return self.is_superuser

class Follower(models.Model):
    user = models.ForeignKey(User, related_name='following', null=True, on_delete=models.SET_NULL)
    follower = models.ForeignKey(User, related_name='follower', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.identifier

    class Meta:
        unique_together = ("user", "follower")

users/forms.py
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm,
                                       PasswordResetForm)
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _
from django.forms.utils import ErrorList
from django.utils.safestring import mark_safe

#forms.Form
#q = forms.CharField(label='search',
#                    widget=forms.TextInput(attrs={'placeholder': 'Search'}))
#forms.ModelForm
#class Meta:
#        model = MyModel
#        widgets = {
#            'name': forms.TextInput(attrs={'placeholder': 'Name'}),}

class CreateAccountForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('identifier', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.error_class = DivErrorList
        #removes default help_text
        for fieldname in ['identifier','email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs = {
                'class': 'wjQ2q'
            }

        self.fields['password1'].widget.attrs = {
            'maxlength': 128,
            'class': 'wjQ2q'
        }

        self.fields['password2'].widget.attrs = {
            'maxlength': 128,
            'class': 'wjQ2q'
        }

#Login view -> default form -> AuthenticationForm
class LoginForm(AuthenticationForm):
    #check AuthenticationForm on github
    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.error_class = DivErrorList

        self.fields['password'].widget.attrs = {
            'maxlength': 128,
            'class': 'wjQ2q',
        }

        self.fields['username'].widget.attrs = {
            'class': 'wjQ2q',
        }

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget.attrs = {
            'class': 'wjQ2q',
        }

class DivErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()

    def as_divs(self):
        if not self: return ''
        #mark_safe() -> Explicitly mark a string as safe for (HTML) output purposes
        #format_html() -> alternative
        return mark_safe('<div class="S8wIM">%s</div>' % ''
            .join(['<div class="bBQfN">%s</div>' % e for e in self]))

#<ul class="errorlist"><li>email<ul class="errorlist"><li>
#Enter a valid email address.</li></ul></li><li>
#password2<ul class="errorlist"><li>This password is too short.
#It must contain at least 8 characters.</l
#i><li>This password is too common.</li></ul></li></ul>

users/views.py
import json
import urllib

from django.conf import settings
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, View
from django.contrib.auth import views as auth_views
from django.contrib import messages
from users.forms import CreateAccountForm, UserPasswordResetForm
from users.models import User
from django.http import JsonResponse
# Create your views here.
#https://www.agiliq.com/blog/2019/01/django-createview/

class SignUpView(CreateView):
    form_class = CreateAccountForm
    template_name = 'users/signup.html'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.

        #Begin reCAPTCHA validation
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req =  urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        #End reCAPTCHA validation

        if result['success']:
            self.object = form.save()
            return redirect(self.get_success_url())
        else:
            messages.error(self.request, 'Invalid reCAPTCHA. Please try again.')

        return render(self.request, 'users/signup.html', {'form':self.form_class})

    #form_invalid --> httpresonse on invalid form

class ValidateIdentififer(View):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('users:signup')

    def get(self, request, *args, **kwargs):
        identifier = self.request.GET.get('identifier', None)
        data = {
            'is_taken': User.objects.filter(identifier__iexact=identifier).exists()
        }
        if data['is_taken']:
            data['error_message'] = 'A user with this username already exists.'
        return JsonResponse(data)

class MyPasswordResetView(auth_views.PasswordResetView):
    success_url = reverse_lazy('password_reset_done')
    template_name = 'password_reset/password_reset_form.html'
    form_class = UserPasswordResetForm

class MyPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'password_reset/password_reset_done.html'

class MyPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy('password_reset_complete')
    template_name = 'password_reset/password_reset_confirm.html'

class MyPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'password_reset/password_reset_complete.html'

users/templates/users/login.html
{% extends 'core.html' %}

  {% block title %}Login{% endblock %}

  {% block content %}
    <div class="onmSW sRz6i">
      <div class="NWmCi iw3Mc">
        <h1 class="JmnD9">SocNet</h1>
        <form method="POST">
          {% csrf_token %}
          <div class="qEdmP">
            {% for field in form %}
            <div class="-MzZI">
              {{ field }}
              <span class="Xvkkr">{{ field.label }}</span>
            </div>
            {% endfor %}
            {% if form.errors %}
              <!-- form.errors is type dict, error_messages in forms.py -->
              {% for error in form.errors.values %}
                {{ error|escape }}
              {% endfor %}
            {% endif %}
            {{ form.password.errors }}
            <div class="GeQQM">
              <button class="PzHaF" type="submit" name="button">
                Application
              </button>
            </div>
            <div class="KcqW8">
              <p><strong>OR</strong></p>
            </div>
            <div class="ypNWu">
              <a class="D5FE7 YnqtJ" href="#">
                <span class="fa fa-facebook-official r5QRp" aria-hidden="true"></span>
                Log in with Facebook
               </a>
            </div>
            <div class="BLEdl">
              <a href="{% url 'users:password_reset' %}" class="hy3nx YnqtJ">Forgot your password?</a>
            </div>
          </div>
        </form>
      </div>
      <div class="ZLIPf iw3Mc">
        <p class="L0AFS">Don't have an account?</p>
        <a class="hgNqZ YnqtJ L0AFS JaDQ4" href="{% url 'users:signup' %}"><strong>Register</strong></a>
      </div>
    </div>
  {% endblock %}

users/templates/users/signup.html
{% extends 'core.html' %}

  {% block title %}Sign up{% endblock %}

  {% block content %}
    <div class="onmSW sRz6i">
      <div class="NWmCi iw3Mc">
        <h1 class="JmnD9">SocNet</h1>
        <form method="post" data-validate-identifier-url="{% url 'users:validate_identifier' %}">
          {% csrf_token %}
          <h2 class="zeyKa">Register to see your friends' photos and videos.</h2>
          <div class="ypNWu">
            <a class="D5FE7 YnqtJ" href="#">
              <span class="fa fa-facebook-official r5QRp" aria-hidden="true"></span>
              Log in with Facebook
             </a>
          </div>
          <div class="KcqW8">
            <p><strong>OR</strong></p>
          </div>
            <div class="KwGlY">
              {% for field in form %}
              <div class="-MzZI">
                {{ field }}
                <span class="Xvkkr">{{ field.label }}</span>
              </div>
              {% endfor %}
            </div>
          <div class="qVJFl">
            <div class="g-recaptcha khkjV" data-sitekey="6LcqeYMbAAAAAKxqkE1EWOZRZ46Huy3uXjTDLSpQ"></div>
          </div>
          {% if form.errors %}
            <!-- form.errors is type dict, error_messages in forms.py -->
            {% for error in form.errors.values %}
              {{ error|escape }}
            {% endfor %}
          {% endif %}
          {{ form.password.errors }}
          {% if messages %}
            {% for message in messages %}
              <div class="S8wIM">
                <div class="bBQfN">
                  {{ message }}
                </div>
              </div>
            {% endfor %}
          {% endif %}
          <div class="GeQQM">
            <button class="PzHaF" type="submit" name="button">
              Application
            </button>
          </div>
        </form>
      </div>
      <div class="ZLIPf iw3Mc">
        <p class="L0AFS">Do you have an account?</p>
        <a class="hgNqZ YnqtJ L0AFS JaDQ4" href="{% url 'users:login' %}"><strong>Application</strong></a>
      </div>
    </div>
    <script src="https://www.google.com/recaptcha/api.js?hl=en" async defer></script>
    <script>
      $('.wjQ2q').change(function(){
        var form = $(this).closest('form');
        $.ajax({
          url: form.attr('data-validate-identifier-url'),
          data: form.serialize(),
          dataType: 'json',
          success: function (data){
            if (data.is_taken){
              $(this).css('border', '1px solid red');
            }
          }
        });
      });
    </script>
  {% endblock %}


<!--
Z9Vv9
ny38G
OhudU
-->